version: '3'
services:
  zookeepern:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    expose:
      - 2181
    ports:
      - 22181:2181
    networks:
      - npdepsnet
    volumes:
      - zookeepern-volume:/bitnami/zookeeper
  kafkan:
    image: bitnami/kafka:latest
    depends_on:
      - zookeepern
    links:
      - zookeepern
    expose:
      - 29092
    ports:
      - 29092:9092
    environment:
      - KAFKA_BROKER_ID= 1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.5.168:29092
      - KAFKA_ZOOKEEPER_CONNECT=zookeepern:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - npdepsnet
    volumes:
      - kafkan-volume:/bitnami/kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"
  observability-server:
    image: percona/pmm-server:2
    restart: always
    expose:
      - 443
    ports:
      - 8443:443
    volumes:
      - pmm-server-volume:/srv
    networks:
      - npdepsnet
volumes:
  zookeepern-volume:
  kafkan-volume:
  pmm-server-volume:
networks:
  npdepsnet:
    driver: bridge