version: '2.24.5'
services:
  provider-db:
    container_name: provider-db-1
    image: mongo:latest
    volumes:
      - provider-db-volume:/data/db
    expose:
      - 27017
    ports:
      - 27018:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    networks:
      - provider-network
  provider-app:
    container_name: provider-app-1
    image: kandolanetwork/data3-node-provider:latest
    environment:
      GRAILS_ENV: development
      DB_HOST: provider-db
      DB_PORT: 27017
      DB_DATABASE: KandolaNodeProvider
      BOOTSTRAP_BASE_URL: https://testconsoleapi.data3.network/
      BOOTSTRAP_PUBSUB_HOST: testpubsub.data3.network
      BOOTSTRAP_PUBSUB_PORT: 9092
      P2P_PORT: 29092

      NODE_IP: 192.168.5.168
      NODE_HOST_NAME: 192.168.5.168
      SELF_PUBSUB_HOST: 192.168.5.168
      SELF_PUBSUB_PORT: 29092

      API_KEY: RT4xsi3IwYbJUQAllcS1jFKB8CJ80F5be1Fw1U92UdmQUXBmpwC90MxfeugdJUKE
      API_SECRET: tgjJ7uLo6z3II22wbpMGSzasRxL1zBEv
      ADDRESS: 0xCd72bC4f5e464Ad4f659Bc62b1155c4183A89828
      PRIVATE_KEY: 20314b398d361035d67d28598f6a31189f88255c983ffc62f8a51ad2d99c35d7

      EXTERNAL_API_ENDPOINT: https://192.168.5.168:9099/api/pricing
    volumes:
      - provider-app-volume:/app/data_home
    expose:
      - 8080
    ports:
      - 8081:8080
    depends_on:
      provider-db:
        condition: service_healthy
    links:
      - provider-db
    networks:
      - provider-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  provider-app-volume:
  provider-db-volume:
networks:
  provider-network:
    driver: bridge